nameOverride: argocd

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: argocd.diogofiaminghi.com.br
    path: /
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
      additionalLabels:
        release: prometheus

repoServer:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
      additionalLabels:
        release: prometheus

dex:
  enabled: true

controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
      additionalLabels:
        release: prometheus
    rules:
      enabled: true
      additionalLabels: 
        release: prometheus
      namespace: monitoring
      spec:
      - alert: ArgoAppMissing
        expr: |
          absent(argocd_app_info) == 1
        for: 15m
        labels:
          severity: critical
        annotations:
          summary: "[Argo CD] No reported applications"
          description: >
            Argo CD has not reported any applications data for the past 15 minutes which
            means that it must be down or not functioning properly.  This needs to be
            resolved for this cloud to continue to maintain state.
      - alert: ArgoAppNotSynced
        expr: |
          argocd_app_info{sync_status!="Synced"} == 1
        for: 12h
        labels:
          severity: warning
        annotations:
          summary: "[{{`{{$labels.name}}`}}] Application not synchronized"
          description: >
            The application [{{`{{$labels.name}}`}} has not been synchronized for over
            12 hours which means that the state of this cloud has drifted away from the
            state inside Git.

configs:
  params:
    server.insecure: true
    server.dex.server: http://argocd-dex-server:5556
    dexserver.disable.tls: true
    server.dex.server.strict.tls: false
  cm:
    url: http://argocd.diogofiaminghi.com.br
    dex.config: |
      connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: Ov23lipyS4mFDeaNqAgs
          clientSecret: 150f3ce2119e5e3639eb4a8e068bd046f1354ea6
          orgs: 
          - name: Treinamento-AgoCD

  rbac:
    policy.default: role:readonly
    policy.csv: |
      p, role:org-admin, applications, *, */*, allow
      p, role:org-admin, clusters, get, *, allow
      p, role:org-admin, repositories, *, *, allow
      p, role:org-admin, logs, get, *, allow
      p, role:org-admin, exec, create, */*, allow
      g, Treinamento-ArgoCD:DevOps, role:org-admin
    scopes: '[groups]'

applicationSet:
  enabled: true
  metrics:
    enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: applicationset.diogofiaminghi.com.br
    path: /